name: "Release dev container features & Generate Documentation"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      # This step will copy our existing install script for the global installation to the devcontainer feature folder to prevent duplication of this script in this repository.
      # This follows the pattern of the devcontainer feature specification: https://containers.dev/implementors/features-distribution/#local-feature-development
      - name: Copy install script for devcontainer feature
        run: cp installation-samples/install-global/install-aikido-hook.sh devcontainer-features/pre-commit-feature/install.sh

      - name: "Publish Features"
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          publish-features: "true"
          base-path-to-features: "./devcontainer-features"
          generate-docs: "false"
